name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Print SonarScanner Path
      run: echo $PATH

    - name: Restore dependencies
      run: dotnet restore dotnet-hello-world/dotnet-hello-world.sln

    - name: Build the project
      run: dotnet build dotnet-hello-world/dotnet-hello-world.sln

    - name: Run tests
      run: dotnet test dotnet-hello-world/dotnet-hello-world.sln

    - name: Set SonarQube Scanner options
      run: export SONAR_SCANNER_OPTS="-Dsonar.scanner.timeout=300"

    - name: Check Java Version in SonarQube Scan
      run: |
        java -version
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet-sonarscanner begin -k:"Github" /d:sonar.host.url="http://ca1.risknucleus.com:9004" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        dotnet build dotnet-hello-world/dotnet-hello-world.sln
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
